# Generated by Django 5.1.4 on 2026-01-07 22:55

import apps.projects.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Automaticky generované: PRJ-YYYY-NNN",
                        max_length=20,
                        unique=True,
                        verbose_name="Číslo projektu",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Název projektu"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Popis")),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="Název klienta"),
                ),
                (
                    "client_ico",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="IČO musí obsahovat přesně 8 číslic",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="IČO",
                    ),
                ),
                (
                    "client_dic",
                    models.CharField(blank=True, max_length=12, verbose_name="DIČ"),
                ),
                (
                    "client_address",
                    models.TextField(blank=True, verbose_name="Adresa klienta"),
                ),
                (
                    "client_contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Kontaktní osoba"
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("site_address", models.TextField(verbose_name="Adresa stavby")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("construction", "Stavba"),
                            ("reconstruction", "Rekonstrukce"),
                            ("repair", "Oprava"),
                            ("installation", "Instalace"),
                            ("demolition", "Demolice"),
                            ("design", "Projektování"),
                            ("other", "Jiné"),
                        ],
                        default="construction",
                        max_length=20,
                        verbose_name="Typ prací",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Plánování"),
                            ("active", "Aktivní"),
                            ("suspended", "Pozastaveno"),
                            ("completed", "Dokončeno"),
                            ("cancelled", "Zrušeno"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "planned_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Plánovaný rozpočet",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum zahájení"
                    ),
                ),
                (
                    "planned_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Plánované dokončení"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Skutečné dokončení"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Poznámky")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manažer projektu",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekty",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.projects.models.project_file_path,
                        verbose_name="Soubor",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Název souboru"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("document", "Dokument"),
                            ("drawing", "Výkres"),
                            ("photo", "Fotografie"),
                            ("contract", "Smlouva"),
                            ("invoice", "Faktura"),
                            ("other", "Jiné"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="Typ souboru",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Popis")),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Velikost (bytes)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.project",
                        verbose_name="Projekt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soubor projektu",
                "verbose_name_plural": "Soubory projektu",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Vytvořeno"),
                            ("updated", "Aktualizováno"),
                            ("status_changed", "Změna stavu"),
                            ("file_added", "Soubor přidán"),
                            ("file_removed", "Soubor odstraněn"),
                        ],
                        max_length=20,
                        verbose_name="Akce",
                    ),
                ),
                ("description", models.TextField(verbose_name="Popis změny")),
                (
                    "old_value",
                    models.TextField(blank=True, verbose_name="Stará hodnota"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, verbose_name="Nová hodnota"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datum a čas"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="projects.project",
                        verbose_name="Projekt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uživatel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historie projektu",
                "verbose_name_plural": "Historie projektu",
                "ordering": ["-created_at"],
            },
        ),
    ]
