# Generated by Django 5.1.4 on 2026-01-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("projects", "0002_add_project_indexes"),
    ]

    operations = [
        # Remove old unique constraint on Project.number
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.CharField(
                help_text="Automaticky generované: PRJ-YYYY-NNN",
                max_length=20,
                verbose_name="Číslo projektu",
            ),
        ),
        # Add company field to Project
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        # Add unique constraint for Project
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("company", "number"), name="unique_project_number_per_company"
            ),
        ),
    ]
