# Generated by Django 5.1.4 on 2026-01-08 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("overdue_invoice", "Faktura po splatnosti"),
                            ("due_soon", "Blížící se splatnost"),
                            ("payment_received", "Platba přijata"),
                            ("project_status", "Změna stavu projektu"),
                        ],
                        max_length=30,
                        verbose_name="Typ notifikace",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="E-mail příjemce"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Předmět")),
                ("message", models.TextField(verbose_name="Zpráva")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Odesláno"),
                            ("failed", "Selhalo"),
                            ("pending", "Čekající"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Chybová zpráva"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Typ objektu"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID objektu"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Odesláno"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Příjemce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log notifikací",
                "verbose_name_plural": "Logy notifikací",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["notification_type", "object_id"],
                        name="notificatio_notific_04b955_idx",
                    ),
                    models.Index(
                        fields=["recipient_email"],
                        name="notificatio_recipie_e7d489_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_01830a_idx"
                    ),
                ],
            },
        ),
    ]
