# Generated by Django 5.1.4 on 2026-01-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "SuperAdmin"),
                    ("admin", "Administrátor"),
                    ("manager", "Manažer"),
                    ("accountant", "Účetní"),
                    ("warehouse", "Skladník"),
                    ("worker", "Pracovník"),
                ],
                default="worker",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="SuperAdmin nemá přiřazenou firmu",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
    ]
