# Generated by Django 5.1.4 on 2026-01-08 00:27

import apps.warehouse.models
import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("settings_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Název kategorie"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Popis")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Pořadí"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorie",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Název")),
                (
                    "sku",
                    models.CharField(
                        help_text="Unikátní identifikátor materiálu",
                        max_length=50,
                        unique=True,
                        verbose_name="Kód/SKU",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("ks", "ks"),
                            ("m", "m"),
                            ("m2", "m²"),
                            ("m3", "m³"),
                            ("kg", "kg"),
                            ("t", "t"),
                            ("l", "l"),
                            ("bal", "bal"),
                            ("rol", "rol"),
                            ("sada", "sada"),
                        ],
                        default="ks",
                        max_length=10,
                        verbose_name="Jednotka",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Nákupní cena",
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        verbose_name="Aktuální zásoba",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                        verbose_name="Minimální zásoba",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.warehouse.models.material_photo_path,
                        verbose_name="Fotografie",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Poznámky")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="warehouse.category",
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="settings_app.supplier",
                        verbose_name="Dodavatel",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materiál",
                "verbose_name_plural": "Materiály",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Číslo příjemky"
                    ),
                ),
                (
                    "receipt_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Datum příjmu"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Koncept"),
                            ("posted", "Zaúčtováno"),
                            ("cancelled", "Zrušeno"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Číslo faktury"
                    ),
                ),
                (
                    "invoice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.warehouse.models.receipt_file_path,
                        verbose_name="Faktura/Dodací list",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Poznámky")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Odpovědná osoba",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_receipts",
                        to="settings_app.supplier",
                        verbose_name="Dodavatel",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Příjemka",
                "verbose_name_plural": "Příjemky",
                "ordering": ["-receipt_date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="StockReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Množství",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Jednotková cena",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=14,
                        verbose_name="Celková cena",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_items",
                        to="warehouse.material",
                        verbose_name="Materiál",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.stockreceipt",
                        verbose_name="Příjemka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Položka příjemky",
                "verbose_name_plural": "Položky příjemky",
            },
        ),
        migrations.CreateModel(
            name="StockWriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Číslo výdejky"
                    ),
                ),
                (
                    "writeoff_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Datum výdeje"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Koncept"),
                            ("posted", "Zaúčtováno"),
                            ("cancelled", "Zrušeno"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Poznámky")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_writeoffs",
                        to="projects.project",
                        verbose_name="Projekt",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_writeoffs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Odpovědná osoba",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Výdejka",
                "verbose_name_plural": "Výdejky",
                "ordering": ["-writeoff_date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="StockWriteOffItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Množství",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Jednotková cena",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=14,
                        verbose_name="Celková cena",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writeoff_items",
                        to="warehouse.material",
                        verbose_name="Materiál",
                    ),
                ),
                (
                    "writeoff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.stockwriteoff",
                        verbose_name="Výdejka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Položka výdejky",
                "verbose_name_plural": "Položky výdejky",
            },
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["sku"], name="warehouse_m_sku_ddb6de_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["name"], name="warehouse_m_name_7d4e7c_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["category"], name="warehouse_m_categor_f10dbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreceipt",
            index=models.Index(fields=["number"], name="warehouse_s_number_dd710f_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreceipt",
            index=models.Index(fields=["status"], name="warehouse_s_status_8f1de3_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreceipt",
            index=models.Index(
                fields=["receipt_date"], name="warehouse_s_receipt_64a9ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockwriteoff",
            index=models.Index(fields=["number"], name="warehouse_s_number_dd3204_idx"),
        ),
        migrations.AddIndex(
            model_name="stockwriteoff",
            index=models.Index(fields=["status"], name="warehouse_s_status_e55165_idx"),
        ),
        migrations.AddIndex(
            model_name="stockwriteoff",
            index=models.Index(
                fields=["writeoff_date"], name="warehouse_s_writeof_f396dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockwriteoff",
            index=models.Index(
                fields=["project"], name="warehouse_s_project_9b57ff_idx"
            ),
        ),
    ]
