# Generated by Django 5.1.4 on 2026-01-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        # Remove old unique constraint on Category.name
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Název kategorie"),
        ),
        # Add company field to Category
        migrations.AddField(
            model_name="category",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categorys",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        # Add unique constraint for Category
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_category_name_per_company"
            ),
        ),
        # Remove old unique constraint on Material.sku
        migrations.AlterField(
            model_name="material",
            name="sku",
            field=models.CharField(
                help_text="Unikátní identifikátor materiálu",
                max_length=50,
                verbose_name="Kód/SKU",
            ),
        ),
        # Add company field to Material
        migrations.AddField(
            model_name="material",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materials",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        # Add unique constraint for Material
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(
                fields=("company", "sku"), name="unique_material_sku_per_company"
            ),
        ),
        # Remove old unique constraint on StockReceipt.number
        migrations.AlterField(
            model_name="stockreceipt",
            name="number",
            field=models.CharField(max_length=20, verbose_name="Číslo příjemky"),
        ),
        # Add company field to StockReceipt
        migrations.AddField(
            model_name="stockreceipt",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stockreceipts",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        # Add unique constraint for StockReceipt
        migrations.AddConstraint(
            model_name="stockreceipt",
            constraint=models.UniqueConstraint(
                fields=("company", "number"),
                name="unique_stockreceipt_number_per_company",
            ),
        ),
        # Remove old unique constraint on StockWriteOff.number
        migrations.AlterField(
            model_name="stockwriteoff",
            name="number",
            field=models.CharField(max_length=20, verbose_name="Číslo výdejky"),
        ),
        # Add company field to StockWriteOff
        migrations.AddField(
            model_name="stockwriteoff",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stockwriteoffs",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        # Add unique constraint for StockWriteOff
        migrations.AddConstraint(
            model_name="stockwriteoff",
            constraint=models.UniqueConstraint(
                fields=("company", "number"),
                name="unique_stockwriteoff_number_per_company",
            ),
        ),
    ]
