# Generated by Django 5.1.4 on 2026-01-07 23:57

import apps.settings_app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "company_name_cs",
                    models.CharField(
                        help_text="Název firmy v češtině",
                        max_length=255,
                        verbose_name="Název firmy (CZ)",
                    ),
                ),
                (
                    "company_name_en",
                    models.CharField(
                        blank=True,
                        help_text="Company name in English",
                        max_length=255,
                        verbose_name="Company Name (EN)",
                    ),
                ),
                (
                    "ico",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="IČO musí obsahovat přesně 8 číslic",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="IČO",
                    ),
                ),
                (
                    "dic",
                    models.CharField(blank=True, max_length=12, verbose_name="DIČ"),
                ),
                (
                    "street",
                    models.CharField(max_length=255, verbose_name="Ulice a č.p."),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Město")),
                ("postal_code", models.CharField(max_length=10, verbose_name="PSČ")),
                (
                    "country",
                    models.CharField(
                        default="Česká republika", max_length=100, verbose_name="Země"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Web")),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Název banky"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Číslo účtu"
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
                ),
                (
                    "swift",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="SWIFT/BIC"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.settings_app.models.company_logo_path,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "stamp",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.settings_app.models.company_stamp_path,
                        verbose_name="Razítko",
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.settings_app.models.company_signature_path,
                        verbose_name="Podpis",
                    ),
                ),
                (
                    "invoice_notes",
                    models.TextField(
                        blank=True,
                        help_text="Text, který se zobrazí na všech fakturách",
                        verbose_name="Poznámky na fakturách",
                    ),
                ),
                (
                    "registration_court",
                    models.CharField(
                        blank=True,
                        help_text='např. "Zapsán v OR vedeném MS v Praze, oddíl C, vložka 12345"',
                        max_length=255,
                        verbose_name="Zápis v OR",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nastavení firmy",
                "verbose_name_plural": "Nastavení firmy",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Název dodavatele"),
                ),
                (
                    "ico",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="IČO musí obsahovat přesně 8 číslic",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="IČO",
                    ),
                ),
                (
                    "dic",
                    models.CharField(blank=True, max_length=12, verbose_name="DIČ"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Kontaktní osoba"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresa")),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Číslo účtu"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Poznámky")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dodavatel",
                "verbose_name_plural": "Dodavatelé",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Název typu práce"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Krátký kód pro identifikaci",
                        max_length=20,
                        unique=True,
                        verbose_name="Kód",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Popis")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ práce",
                "verbose_name_plural": "Typy prací",
                "ordering": ["name"],
            },
        ),
    ]
