# Generated by Django 5.1.4 on 2026-01-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("settings_app", "0001_initial"),
    ]

    operations = [
        # Add company field to CompanySettings (OneToOne)
        migrations.AddField(
            model_name="companysettings",
            name="company",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        # Add company field to Supplier
        migrations.AddField(
            model_name="supplier",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        # Remove old unique constraints on WorkType
        migrations.AlterField(
            model_name="worktype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Název typu práce"),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="code",
            field=models.CharField(
                help_text="Krátký kód pro identifikaci",
                max_length=20,
                verbose_name="Kód",
            ),
        ),
        # Add company field to WorkType
        migrations.AddField(
            model_name="worktype",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_types",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        # Add unique constraints for WorkType
        migrations.AddConstraint(
            model_name="worktype",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_worktype_name_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="worktype",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_worktype_code_per_company"
            ),
        ),
    ]
