# Generated by Django 5.1.4 on 2026-01-21 12:00

from django.db import migrations


def create_default_company_and_assign(apps, schema_editor):
    """
    Create a default company and assign all existing records to it.
    This is a one-time migration for existing data.
    """
    Company = apps.get_model("companies", "Company")

    # Models that need company assignment
    Category = apps.get_model("warehouse", "Category")
    Material = apps.get_model("warehouse", "Material")
    StockReceipt = apps.get_model("warehouse", "StockReceipt")
    StockWriteOff = apps.get_model("warehouse", "StockWriteOff")
    Project = apps.get_model("projects", "Project")
    Invoice = apps.get_model("invoices", "Invoice")
    Payment = apps.get_model("invoices", "Payment")
    CompanySettings = apps.get_model("settings_app", "CompanySettings")
    Supplier = apps.get_model("settings_app", "Supplier")
    WorkType = apps.get_model("settings_app", "WorkType")

    # Check if there are any records that need a company
    has_records = (
        Category.objects.exists() or
        Material.objects.exists() or
        StockReceipt.objects.exists() or
        StockWriteOff.objects.exists() or
        Project.objects.exists() or
        Invoice.objects.exists() or
        Payment.objects.exists() or
        CompanySettings.objects.exists() or
        Supplier.objects.exists() or
        WorkType.objects.exists()
    )

    if not has_records:
        # No existing records, no need to create default company
        return

    # Create or get default company
    default_company, created = Company.objects.get_or_create(
        slug="default-company",
        defaults={
            "name": "Default Company",
            "ico": "",
            "dic": "",
            "street": "",
            "city": "",
            "postal_code": "",
            "country": "Česká republika",
            "is_active": True,
        }
    )

    # Assign all existing records to default company
    Category.objects.filter(company__isnull=True).update(company=default_company)
    Material.objects.filter(company__isnull=True).update(company=default_company)
    StockReceipt.objects.filter(company__isnull=True).update(company=default_company)
    StockWriteOff.objects.filter(company__isnull=True).update(company=default_company)
    Project.objects.filter(company__isnull=True).update(company=default_company)
    Invoice.objects.filter(company__isnull=True).update(company=default_company)
    Payment.objects.filter(company__isnull=True).update(company=default_company)
    CompanySettings.objects.filter(company__isnull=True).update(company=default_company)
    Supplier.objects.filter(company__isnull=True).update(company=default_company)
    WorkType.objects.filter(company__isnull=True).update(company=default_company)


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - set company to NULL for all records.
    """
    Category = apps.get_model("warehouse", "Category")
    Material = apps.get_model("warehouse", "Material")
    StockReceipt = apps.get_model("warehouse", "StockReceipt")
    StockWriteOff = apps.get_model("warehouse", "StockWriteOff")
    Project = apps.get_model("projects", "Project")
    Invoice = apps.get_model("invoices", "Invoice")
    Payment = apps.get_model("invoices", "Payment")
    CompanySettings = apps.get_model("settings_app", "CompanySettings")
    Supplier = apps.get_model("settings_app", "Supplier")
    WorkType = apps.get_model("settings_app", "WorkType")

    Category.objects.all().update(company=None)
    Material.objects.all().update(company=None)
    StockReceipt.objects.all().update(company=None)
    StockWriteOff.objects.all().update(company=None)
    Project.objects.all().update(company=None)
    Invoice.objects.all().update(company=None)
    Payment.objects.all().update(company=None)
    CompanySettings.objects.all().update(company=None)
    Supplier.objects.all().update(company=None)
    WorkType.objects.all().update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("warehouse", "0002_add_company_field"),
        ("projects", "0003_add_company_field"),
        ("invoices", "0003_add_company_field"),
        ("settings_app", "0002_add_company_field"),
    ]

    operations = [
        migrations.RunPython(
            create_default_company_and_assign,
            reverse_code=reverse_migration,
        ),
    ]
