# Generated by Django 5.1.4 on 2026-01-21 12:00

from django.db import migrations
from django.utils.text import slugify


def create_default_company_and_assign(apps, schema_editor):
    """
    Create a default company and assign all existing records to it.
    Uses CompanySettings data if available to create the company.
    This is a one-time migration for existing data.
    """
    Company = apps.get_model("companies", "Company")
    User = apps.get_model("users", "User")

    # Models that need company assignment
    Category = apps.get_model("warehouse", "Category")
    Material = apps.get_model("warehouse", "Material")
    StockReceipt = apps.get_model("warehouse", "StockReceipt")
    StockWriteOff = apps.get_model("warehouse", "StockWriteOff")
    Project = apps.get_model("projects", "Project")
    Invoice = apps.get_model("invoices", "Invoice")
    Payment = apps.get_model("invoices", "Payment")
    CompanySettings = apps.get_model("settings_app", "CompanySettings")
    Supplier = apps.get_model("settings_app", "Supplier")
    WorkType = apps.get_model("settings_app", "WorkType")

    # Check if there are any records that need a company
    has_records = (
        Category.objects.exists() or
        Material.objects.exists() or
        StockReceipt.objects.exists() or
        StockWriteOff.objects.exists() or
        Project.objects.exists() or
        Invoice.objects.exists() or
        Payment.objects.exists() or
        CompanySettings.objects.exists() or
        Supplier.objects.exists() or
        WorkType.objects.exists() or
        User.objects.filter(role__in=['admin', 'manager', 'accountant', 'warehouse', 'worker']).exists()
    )

    if not has_records:
        # No existing records, no need to create default company
        return

    # Try to get company data from existing CompanySettings
    existing_settings = CompanySettings.objects.filter(company__isnull=True).first()

    if existing_settings:
        # Use data from CompanySettings
        company_name = existing_settings.company_name_cs or "Default Company"
        company_data = {
            "name": company_name,
            "ico": existing_settings.ico or "",
            "dic": existing_settings.dic or "",
            "street": existing_settings.street or "",
            "city": existing_settings.city or "",
            "postal_code": existing_settings.postal_code or "",
            "country": existing_settings.country or "Česká republika",
            "phone": existing_settings.phone or "",
            "email": existing_settings.email or "",
            "website": existing_settings.website or "",
            "bank_name": existing_settings.bank_name or "",
            "bank_account": existing_settings.bank_account or "",
            "iban": existing_settings.iban or "",
            "swift": existing_settings.swift or "",
            "is_active": True,
        }
        company_slug = slugify(company_name)[:50] or "default-company"
    else:
        # Use default values
        company_name = "Default Company"
        company_data = {
            "name": company_name,
            "ico": "",
            "dic": "",
            "street": "",
            "city": "",
            "postal_code": "",
            "country": "Česká republika",
            "is_active": True,
        }
        company_slug = "default-company"

    # Create or get default company
    default_company, created = Company.objects.get_or_create(
        slug=company_slug,
        defaults=company_data
    )

    # Assign all existing records to default company
    Category.objects.filter(company__isnull=True).update(company=default_company)
    Material.objects.filter(company__isnull=True).update(company=default_company)
    StockReceipt.objects.filter(company__isnull=True).update(company=default_company)
    StockWriteOff.objects.filter(company__isnull=True).update(company=default_company)
    Project.objects.filter(company__isnull=True).update(company=default_company)
    Invoice.objects.filter(company__isnull=True).update(company=default_company)
    Payment.objects.filter(company__isnull=True).update(company=default_company)
    CompanySettings.objects.filter(company__isnull=True).update(company=default_company)
    Supplier.objects.filter(company__isnull=True).update(company=default_company)
    WorkType.objects.filter(company__isnull=True).update(company=default_company)

    # Assign users to default company (except superadmin)
    User.objects.filter(
        company__isnull=True
    ).exclude(
        role='superadmin'
    ).update(company=default_company)


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - set company to NULL for all records.
    """
    User = apps.get_model("users", "User")
    Category = apps.get_model("warehouse", "Category")
    Material = apps.get_model("warehouse", "Material")
    StockReceipt = apps.get_model("warehouse", "StockReceipt")
    StockWriteOff = apps.get_model("warehouse", "StockWriteOff")
    Project = apps.get_model("projects", "Project")
    Invoice = apps.get_model("invoices", "Invoice")
    Payment = apps.get_model("invoices", "Payment")
    CompanySettings = apps.get_model("settings_app", "CompanySettings")
    Supplier = apps.get_model("settings_app", "Supplier")
    WorkType = apps.get_model("settings_app", "WorkType")

    User.objects.all().update(company=None)
    Category.objects.all().update(company=None)
    Material.objects.all().update(company=None)
    StockReceipt.objects.all().update(company=None)
    StockWriteOff.objects.all().update(company=None)
    Project.objects.all().update(company=None)
    Invoice.objects.all().update(company=None)
    Payment.objects.all().update(company=None)
    CompanySettings.objects.all().update(company=None)
    Supplier.objects.all().update(company=None)
    WorkType.objects.all().update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0002_add_company_and_superadmin"),
        ("warehouse", "0002_add_company_field"),
        ("projects", "0003_add_company_field"),
        ("invoices", "0003_add_company_field"),
        ("settings_app", "0002_add_company_field"),
    ]

    operations = [
        migrations.RunPython(
            create_default_company_and_assign,
            reverse_code=reverse_migration,
        ),
    ]
