# Generated by Django 5.1.4 on 2026-01-07 23:24

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Číslo faktury"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Datum vystavení"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Datum splatnosti")),
                (
                    "taxable_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum zdanitelného plnění"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="Název klienta"),
                ),
                (
                    "client_ico",
                    models.CharField(blank=True, max_length=8, verbose_name="IČO"),
                ),
                (
                    "client_dic",
                    models.CharField(blank=True, max_length=15, verbose_name="DIČ"),
                ),
                (
                    "client_address",
                    models.TextField(blank=True, verbose_name="Adresa klienta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Koncept"),
                            ("issued", "Vystaveno"),
                            ("partially_paid", "Částečně uhrazeno"),
                            ("paid", "Uhrazeno"),
                            ("overdue", "Po splatnosti"),
                            ("cancelled", "Zrušeno"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Poznámky")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Interní poznámky"),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Číslo účtu"
                    ),
                ),
                (
                    "variable_symbol",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Variabilní symbol"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="projects.project",
                        verbose_name="Projekt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faktura",
                "verbose_name_plural": "Faktury",
                "ordering": ["-issue_date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Vytvořeno"),
                            ("updated", "Aktualizováno"),
                            ("issued", "Vystaveno"),
                            ("cancelled", "Zrušeno"),
                            ("payment_added", "Platba přidána"),
                            ("payment_removed", "Platba odstraněna"),
                            ("status_changed", "Změna stavu"),
                        ],
                        max_length=30,
                        verbose_name="Akce",
                    ),
                ),
                ("description", models.TextField(verbose_name="Popis")),
                (
                    "old_value",
                    models.TextField(blank=True, verbose_name="Předchozí hodnota"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, verbose_name="Nová hodnota"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datum"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="invoices.invoice",
                        verbose_name="Faktura",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uživatel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historie faktury",
                "verbose_name_plural": "Historie faktur",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Název")),
                ("description", models.TextField(blank=True, verbose_name="Popis")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Množství",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("ks", "ks"),
                            ("hod", "hod"),
                            ("m", "m"),
                            ("m2", "m²"),
                            ("m3", "m³"),
                            ("kg", "kg"),
                            ("t", "t"),
                            ("km", "km"),
                            ("den", "den"),
                            ("komplet", "komplet"),
                        ],
                        default="ks",
                        max_length=20,
                        verbose_name="Jednotka",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Jednotková cena",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=14,
                        verbose_name="Celková cena",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Pořadí"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                        verbose_name="Faktura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Položka faktury",
                "verbose_name_plural": "Položky faktury",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Datum platby"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Částka",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Hotovost"),
                            ("bank", "Bankovní převod"),
                            ("card", "Kartou"),
                        ],
                        default="bank",
                        max_length=20,
                        verbose_name="Způsob platby",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Číslo dokladu"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Poznámky")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.invoice",
                        verbose_name="Faktura",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualizoval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platba",
                "verbose_name_plural": "Platby",
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["number"], name="invoices_in_number_9bae8b_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="invoices_in_status_cec546_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["project"], name="invoices_in_project_3171df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="invoices_in_due_dat_6cc0ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["issue_date"], name="invoices_in_issue_d_588fba_idx"
            ),
        ),
    ]
