# Generated by Django 5.1.4 on 2026-01-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("invoices", "0002_invoice_invoice_type"),
    ]

    operations = [
        # Remove old unique constraint on Invoice.number
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(max_length=20, verbose_name="Číslo faktury"),
        ),
        # Add company field to Invoice
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        # Add unique constraint for Invoice
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("company", "number"), name="unique_invoice_number_per_company"
            ),
        ),
        # Add company field to Payment
        migrations.AddField(
            model_name="payment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
    ]
